"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.productRouter = void 0;
const express_1 = require("express");
const productController_1 = require("../controllers/productController");
exports.productRouter = express_1.Router();
const controller = new productController_1.productController();
exports.productRouter.post('/product', controller.addproduct);
exports.productRouter.post('/quantity', controller.addQuantity);
exports.productRouter.delete('/deleteproduct', controller.DeleteProduct);
